# Generated by Django 3.0.7 on 2020-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('deck_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('words', models.TextField()),
                ('published', models.DateField(verbose_name='Uploaded on')),
                ('likes', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('decks_downloaded', models.IntegerField()),
                ('decks_uploaded', models.IntegerField()),
            ],
        ),
    ]
