# Generated by Django 3.0.7 on 2020-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='decks',
            name='user_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
