# Generated by Django 3.0.7 on 2020-06-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_auto_20200624_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='comments',
        ),
    ]
