# Generated by Django 3.0.7 on 2020-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0005_remove_deck_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='downloads',
            field=models.IntegerField(null=True),
        ),
    ]
