# Generated by Django 3.0.7 on 2020-08-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0006_deck_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='likes',
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
