# Generated by Django 3.0.7 on 2020-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0007_auto_20200824_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(verbose_name='Account created on')),
            ],
        ),
    ]
