# Generated by Django 3.0.7 on 2020-10-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0009_deck_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='hashtags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
